DROP TABLE IF EXISTS USERS, FILMS, FRIENDS, FILMS_GENRES, GENRES, MPA, LIKES CASCADE;

create table if not exists users (
    user_id INTEGER generated by default as identity primary key,
    email CHARACTER VARYING(60) not null,
    login CHARACTER VARYING(60) not null,
    name CHARACTER VARYING(60) not null,
    birthday DATE not null
);

create table if not exists mpa (
    id INTEGER not null,
    mpa_name CHARACTER VARYING(30) not null,
    PRIMARY KEY (id)
);

create table if not exists genres (
    id INTEGER UNIQUE NOT NULL,
    genre_name VARCHAR(60) NOT NULL,
    PRIMARY KEY (id)
);

create table if not exists films (
    film_id INTEGER generated by default as identity primary key,
    name CHARACTER VARYING(100) not null,
    description CHARACTER VARYING(200) not null,
    release_date DATE not null,
    duration INTEGER not null,
    id INTEGER REFERENCES mpa (id) ON DELETE SET NULL,
    rate INTEGER
);

create table if not exists friends (
    user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
);

create table if not exists film_genres (
    id INTEGER REFERENCES genres (id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, id)
);

create table if not exists likes (
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);